name: Deploy GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  # generate-openapi-spec:
  #   runs-on: windows-latest
  #   steps:
  #     - uses: actions/checkout@v3
  #     - name: Upload openapi.json
  #       uses: actions/upload-artifact@v3
  #       with:
  #         name: spec-file
  #         path: public/openapi.json
  deploy:
    runs-on: ubuntu-latest
    steps:
        - name: Generate Swagger UI
          uses: Legion2/swagger-ui-action@v1
          with:
            output: publich
            spec-file: openapi.json
        - name: Deploy to GitHub Pages
          uses: peaceiris/actions-gh-pages@v3
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            publish_dir: swagger-ui
